Fix/#91 functions rewrite rule
kanko-dori/code-jinro pull request #92
Opened 2020-08-10 13:26 UTC by ssssota

closes #91 

## why

ルーム作成ボタンが正常に動作していなかった（４０４）

## what

リライトルールとエンドポイントを調整した

2020-08-11 10:58 UTC, onsd requested changes

2020-08-11 10:58 UTC, onsd commented on functions/src/handler.ts
> +  if (!['production', 'staging', 'dev'].includes(stage)) {
順番違いで申し訳ないけどここ変更が必要　？

2020-08-11 11:41 UTC, ssssota commented on functions/src/handler.ts
> +  if (!['production', 'staging', 'dev'].includes(stage)) {
僕的にこっち先に修正してあとから気になるなぁって #98 を建てたのでいらないです

2020-08-15 11:07 UTC, ssssota commented
@watamoko これ

2022-07-22 07:48 UTC, closed without merging

2022-07-22 07:50 UTC, onsd commented
なつい